correlation_thred: 0.85
laser_topic_sub: /velodyne_cloud_registered
odom_topic_sub: /integrated_to_map
cloud_image_topic_pub: /neg_detect/cloud_image
ground_topic_pub: /neg_detect/ground_cloud
neg_obs_topic_pub: /neg_detect/stair_topic_pub
is_stair_topic_pub: /neg_detect/is_stair_topic_pub
stair_poses_topic_pub: /neg_detect/stair_poses_topic_pub
kernel_server_topic: /neg_detect/kernel_serve_topic
kernel_filename: stair_kernel.txt
cluster_filter_size: 10
cluster_radius: 1.0
slope_thresh: 50.0
flat_thresh: 10.0
kMeans_iters:  50
col_filter_size: 25
frame_filter_size: 20

